### ISSUE TITLE
oom_score_adj cannot by read on Android 6

### ISSUE THREAD

**Issue by samlu** [jaredrummler/AndroidProcesses#1]
-r-------- u0_a111  u0_a111         0 2015-10-22 17:37 oom_score_adj

Android 6 disables 3rd party apps to read oom_score_adj. 
Is there any solution to decide which foreground process is top app?

**Comment by jaredrummler** [comment]
I need to look into this more. As of now, I think the only way to know the foreground app on Android M is to use UsageStatsManager. I *think* that if your process' oom_score is 0 and the policy (see /proc/[pid]/stat) is "fg" then *most likely* your process is the foreground application.

**Comment by samlu** [comment]
Thanks for the update. I did a test on my Nexus 5(Android 6). It looks like that we can use the value of oom_score to sort apps if we failed to open oom_score_adj file. FYI.

**Comment by marcinpaszylk** [comment]
Usually app with lowers oom_score is on the foreground, but on Android 6.0 system apps (like com.android.settings) are not listed in output of "toolbox ps -p". I've comared the output of toolbox command run from adb shell and executing it from java code - the second list is shorter.
Have you found a way to get full list of running processes?

**Comment by jaredrummler** [comment]
@marcinpaszylk unfortunately, when you run `toolbox ps` from your app you don't have the same SELinux context/privilege as you do when you run the command from adb. List the /proc directory using `adb shell toolbox ls -Z /proc` and you will notice that some pids have contexts like `u:r:system_app:s0` or `u:r:platform_app:s0`. When you run `toolbox ps` or get processes using this library your app most likely has the third party app context (`u:r:untrusted_app:s0`). Under SELinux, this makes reading those directories impossible. That is why you get a shorter list when you are running `toolbox ps` from your app.

More info see https://su.chainfire.eu/#selinux

Because of these elevated contexts for system apps it is currently impossible to get all processes on Android 5.1+ unless you use something like UsageStatsManager.

**Comment by jaredrummler** [comment]
I'm going to close this issue. There doesn't seem to be a 100% foolproof way to determine the foreground app without root access. UsageStatsManager should be used if you need this functionality.
