### ISSUE TITLE
setting not showing

### ISSUE THREAD

**Issue by fredul** [jaredrummler/AndroidProcesses#18]
Hi,

I do not see the process of "settings" when I entered settings. Is it supposed to "not showing"?

Also can you provide an example how to get the foreground process package name, such as "facebook" or "gallery"?

Thanks.

**Comment by jaredrummler** [comment]
The library's main usage should be to get a list of running apps. If you need to know the foreground app then you should use UsageStatsManager. The Settings app may not appear in the list because your app process cannot read system app process info (it has a higher [SELinux context](https://su.chainfire.eu/#selinux)).
