### ISSUE TITLE
stack top

### ISSUE THREAD

**Issue by MrHuJianQiang** [jaredrummler/AndroidProcesses#33]
How to obtain the top of the stack application package name

**Comment by dunghc** [comment]
the same question. pls help me.

**Comment by jaredrummler** [comment]
This is not available using this library. This library provides a way to get process info that you would otherwise get by running ps in a shell, only it's faster and provides more details about each process. I would suggest looking on StackOverflow for an answer to your question. I would look into ActivityLifecycleCallbacks before considering UsageStatsManager. Most applications don't need to know the top of the stack application package name.
